"""
Django settings for network_tickets project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _load_simple_env_file(env_path: Path):
    """
    Minimal .env loader (KEY=VALUE, ignores comments).
    Only sets variables that are not already present in the environment.
    """
    try:
        if not env_path.exists():
            return
        for raw in env_path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val
    except Exception:
        # Never hard-fail settings import due to dotenv parsing.
        return

# Load project-level env file if present (e.g. for REDIS_URL, secrets, etc.)
# NOTE: `.env` is gitignored in this repo; use `env.conf` instead.
_load_simple_env_file(BASE_DIR / "env.conf")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-60o3qg1ej0ao^)e4e4=nx&&i&4x#g4o9$vzb(11)#_6-(-++15'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


CSRF_TRUSTED_ORIGINS = [
    "https://cmhk-it-netcare.com",
    "https://www.cmhk-it-netcare.com",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auto_tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'network_tickets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'network_tickets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'auto_tickets',
        'USER': 'zc',
        'PASSWORD': 'zc8131868',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Cache
# - For multi-worker deployments, use a SHARED cache backend (Redis recommended)
# - Set `REDIS_URL`, e.g. redis://127.0.0.1:6379/1
#
# Django 5 ships with a Redis cache backend, but you still need the `redis` Python
# package installed on the server for it to work.
REDIS_URL = os.getenv("REDIS_URL", "").strip()

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 60 * 60,  # 1 hour default
        }
    }
else:
    # Development fallback (NOT shared across processes)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "it_network_locmem",
            "TIMEOUT": 60 * 60,  # 1 hour default
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static'),
]

# 媒体文件根目录
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# 媒体文件URL前缀
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Network speed monitor configuration
NETWORK_SPEED_SITES = [
    {
        "name": "CMHK Portal",
        "url": "https://www.hk.chinamobile.com",
    },
    {
        "name": "Google",
        "url": "https://www.google.com",
    },
    {
        "name": "ITSR",
        "url": "https://ncoa.cmhktry.com/todo/center?lang=en-US&open_in_browser=true&tenantID=cmhk&version=0.1.6&from=workplace_home",
    },
]

NETWORK_SPEED_THRESHOLDS = {
    "good": 300,   # ms
    "warning": 800,  # ms
}

NETWORK_SPEED_TIMEOUT = 5  # seconds