filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://elasticsearch.qytopensource.com:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "Cisc0123"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.cer"]

setup.template.name: "qytang-netflow"
setup.template.pattern: "filebeat-*"
setup.ilm.enabled: false